Appending new data of melanoma to the original dataset. 
New data consists of the same melanoma images from original dataset and "Augmented" versions of them.
After appending new data, duplicates will also be dropped.

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(r'.\train_original.csv')
print(df.head(10))

                 id label
0  ISIC_0024306.jpg    nv
1  ISIC_0024307.jpg    nv
2  ISIC_0024308.jpg    nv
3  ISIC_0024309.jpg    nv
4  ISIC_0024310.jpg   mel
5  ISIC_0024311.jpg    nv
6  ISIC_0024312.jpg   bkl
7  ISIC_0024313.jpg   mel
8  ISIC_0024314.jpg    nv
9  ISIC_0024315.jpg   mel

In [23]:
df['label'].value_counts()

nv       6705
mel      1113
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: label, dtype: int64

In [7]:
df2 = pd.read_csv(r'.\melanoma\melanoma.csv')
print(df2.head(10))

                      id label
0        AUG_0_3769.jpeg   mel
1         AUG_0_219.jpeg   mel
2        AUG_0_7680.jpeg   mel
3        AUG_0_2528.jpeg   mel
4        AUG_0_7395.jpeg   mel
5  AUGmented_0_1114.jpeg   mel
6        AUG_0_2197.jpeg   mel
7  AUGmented_0_9877.jpeg   mel
8        AUG_0_1241.jpeg   mel
9        AUG_0_2894.jpeg   mel

In [24]:
df2['label'].value_counts()

mel    5340
Name: label, dtype: int64

In [8]:
newdf = df.append(df2)

In [12]:
newdf = newdf.drop_duplicates()

In [13]:
newdf

                         id  label
0          ISIC_0024306.jpg     nv
1          ISIC_0024307.jpg     nv
2          ISIC_0024308.jpg     nv
3          ISIC_0024309.jpg     nv
4          ISIC_0024310.jpg    mel
5          ISIC_0024311.jpg     nv
6          ISIC_0024312.jpg    bkl
7          ISIC_0024313.jpg    mel
8          ISIC_0024314.jpg     nv
9          ISIC_0024315.jpg    mel
10         ISIC_0024316.jpg     nv
11         ISIC_0024317.jpg     nv
12         ISIC_0024318.jpg     df
13         ISIC_0024319.jpg     nv
14         ISIC_0024320.jpg     nv
15         ISIC_0024321.jpg     nv
16         ISIC_0024322.jpg     nv
17         ISIC_0024323.jpg    mel
18         ISIC_0024324.jpg    bkl
19         ISIC_0024325.jpg     nv
20         ISIC_0024326.jpg     nv
21         ISIC_0024327.jpg     nv
22         ISIC_0024328.jpg     nv
23         ISIC_0024329.jpg  akiec
24         ISIC_0024330.jpg     df
25         ISIC_0024331.jpg    bcc
26         ISIC_0024332.jpg    bcc
27         ISIC_0024333.jpg    mel
28         ISIC_0024334.jpg     nv
29         ISIC_0024335.jpg     nv
...                     ...    ...
5309         AUG_0_324.jpeg    mel
5310        AUG_0_9609.jpeg    mel
5311        AUG_0_2045.jpeg    mel
5312  AUGmented_0_3151.jpeg    mel
5313        AUG_0_2415.jpeg    mel
5315        AUG_0_4938.jpeg    mel
5316        AUG_0_6905.jpeg    mel
5317        AUG_0_4312.jpeg    mel
5318  AUGmented_0_4944.jpeg    mel
5319  AUGmented_0_2193.jpeg    mel
5320        AUG_0_1540.jpeg    mel
5321        AUG_0_6285.jpeg    mel
5322        AUG_0_5850.jpeg    mel
5323        AUG_0_4742.jpeg    mel
5324  AUGmented_0_6580.jpeg    mel
5325        AUG_0_7494.jpeg    mel
5326        AUG_0_2696.jpeg    mel
5327        AUG_0_2383.jpeg    mel
5328  AUGmented_0_9730.jpeg    mel
5329        AUG_0_2229.jpeg    mel
5330  AUGmented_0_1750.jpeg    mel
5331  AUGmented_0_6095.jpeg    mel
5332  AUGmented_0_8121.jpeg    mel
5333        AUG_0_7882.jpeg    mel
5334        AUG_0_6790.jpeg    mel
5335        AUG_0_5915.jpeg    mel
5336        AUG_0_7928.jpeg    mel
5337        AUG_0_4607.jpeg    mel
5338         AUG_0_518.jpeg    mel
5339        AUG_0_3438.jpeg    mel

[14686 rows x 2 columns]

In [14]:
newdf.to_csv("train.csv",index=False)

In [22]:
newdf['label'].value_counts()

nv       6705
mel      5784
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: label, dtype: int64